In [1]:
import polars as pl

In [5]:
base_dir = "/Users/zhangyubo/Projects/QuantData/Ashare/"

In [ ]:
df = pl.read_parquet("base_dir/stock_info/finance_capital/000001_SZ_cap.parquet")

In [3]:
df

shape: (181, 7)
┌───────────┬───────────┬───────────────┬───────────────┬───────────────┬──────────────┬───────────┐
│ m_timetag ┆ m_anntime ┆ total_capital ┆ circulating_c ┆ restrict_circ ┆ freeFloatCap ┆ m_quarter │
│ ---       ┆ ---       ┆ ---           ┆ apital        ┆ ulating_capit ┆ ital         ┆ ---       │
│ str       ┆ str       ┆ f64           ┆ ---           ┆ al            ┆ ---          ┆ f64       │
│           ┆           ┆               ┆ f64           ┆ ---           ┆ f64          ┆           │
│           ┆           ┆               ┆               ┆ f64           ┆              ┆           │
╞═══════════╪═══════════╪═══════════════╪═══════════════╪═══════════════╪══════════════╪═══════════╡
│ 19910403  ┆ 19910403  ┆ 4.8500171e7   ┆ 2.65e7        ┆ 0.0           ┆ 0.0          ┆ 0.0       │
│ 19910630  ┆ 19910630  ┆ 4.8500171e7   ┆ 2.65e7        ┆ 0.0           ┆ 0.0          ┆ 0.0       │
│ 19910930  ┆ 19910930  ┆ 4.8500171e7   ┆ 2.65e7        ┆ 0.0           ┆ 0.0          ┆ 0.0       │
│ 19911231  ┆ 19911231  ┆ 8.9751643e7   ┆ 3.9490723e7   ┆ 0.0           ┆ 0.0          ┆ 0.0       │
│ 19920331  ┆ 19920331  ┆ 8.9751643e7   ┆ 3.9490723e7   ┆ 0.0           ┆ 0.0          ┆ 0.0       │
│ …         ┆ …         ┆ …             ┆ …             ┆ …             ┆ …            ┆ …         │
│ 20240331  ┆ 20240331  ┆ 1.9406e10     ┆ 1.9406e10     ┆ 0.0           ┆ 8.6009e9     ┆ 0.0       │
│ 20240630  ┆ 20240816  ┆ 1.9406e10     ┆ 1.9406e10     ┆ 0.0           ┆ 8.6010e9     ┆ 0.0       │
│ 20240930  ┆ 20240930  ┆ 1.9406e10     ┆ 1.9406e10     ┆ 0.0           ┆ 8.6010e9     ┆ 0.0       │
│ 20241231  ┆ 20250315  ┆ 1.9406e10     ┆ 1.9406e10     ┆ 0.0           ┆ 8.6009e9     ┆ 0.0       │
│ 20250630  ┆ 20250823  ┆ 1.9406e10     ┆ 1.9406e10     ┆ 0.0           ┆ 8.6010e9     ┆ 0.0       │
└───────────┴───────────┴───────────────┴───────────────┴───────────────┴──────────────┴───────────┘

In [8]:
df2 = pl.read_parquet(f"{base_dir}/stock_day/600004_SH.parquet")

In [9]:
df2

shape: (1_434, 8)
┌───────────────┬────────┬────────┬────────┬────────┬────────┬──────────────┬─────────────┐
│ time          ┆ open   ┆ high   ┆ low    ┆ close  ┆ volume ┆ amount       ┆ suspendFlag │
│ ---           ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---          ┆ ---         │
│ i64           ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    ┆ f64          ┆ i32         │
╞═══════════════╪════════╪════════╪════════╪════════╪════════╪══════════════╪═════════════╡
│ 1577894400000 ┆ 17.141 ┆ 17.201 ┆ 16.981 ┆ 17.101 ┆ 177924 ┆ 3.11394028e8 ┆ 0           │
│ 1577980800000 ┆ 17.191 ┆ 17.201 ┆ 16.891 ┆ 16.961 ┆ 163146 ┆ 2.84126626e8 ┆ 0           │
│ 1578240000000 ┆ 16.821 ┆ 16.821 ┆ 16.531 ┆ 16.661 ┆ 214553 ┆ 3.6601e8     ┆ 0           │
│ 1578326400000 ┆ 16.641 ┆ 16.871 ┆ 16.481 ┆ 16.841 ┆ 168007 ┆ 2.872421e8   ┆ 0           │
│ 1578412800000 ┆ 16.791 ┆ 16.911 ┆ 16.531 ┆ 16.671 ┆ 166815 ┆ 2.8496e8     ┆ 0           │
│ …             ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …            ┆ …           │
│ 1764086400000 ┆ 9.62   ┆ 9.69   ┆ 9.59   ┆ 9.6    ┆ 121262 ┆ 1.1679e8     ┆ 0           │
│ 1764172800000 ┆ 9.61   ┆ 9.67   ┆ 9.56   ┆ 9.62   ┆ 117054 ┆ 1.12571009e8 ┆ 0           │
│ 1764259200000 ┆ 9.62   ┆ 9.68   ┆ 9.57   ┆ 9.65   ┆ 110536 ┆ 1.0648e8     ┆ 0           │
│ 1764518400000 ┆ 9.65   ┆ 9.66   ┆ 9.58   ┆ 9.66   ┆ 162085 ┆ 1.55809703e8 ┆ 0           │
│ 1764604800000 ┆ 9.66   ┆ 9.77   ┆ 9.61   ┆ 9.75   ┆ 176033 ┆ 1.71170922e8 ┆ 0           │
└───────────────┴────────┴────────┴────────┴────────┴────────┴──────────────┴─────────────┘